### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by switck** [switck/libngu#1]
- [x] create ripemd160 and sha512 (maybe taking from from mbedtls, but not axtls) 
- [x] expose HMAC stuff from there too?
- [x] create mpy interface for libsecp256k1 (thin?)
- [x] bip39 wordlist
- [x] bip32 nodes
- [x] codecs for bitcoin: base58, bech32
- [x] AES basics
- [x] TRNG
